package com.example.expensetracker.util

import android.content.Context
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import java.io.OutputStream
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import kotlin.math.min

object ReportPdfExporter {

    /**
     * Writes a simple, professional PDF report to the provided OutputStream.
     * (No storage permission needed if you use SAF CreateDocument in Compose.)
     */
    fun writeMonthlyReportPdf(
        context: Context,
        output: OutputStream,
        title: String,
        monthLabel: String,
        incomeText: String,
        expenseText: String,
        balanceText: String,
        categories: List<Pair<String, String>> // (label, amountText)
    ) {
        // A4 @ 72dpi-ish points
        val pageWidth = 595
        val pageHeight = 842

        val doc = PdfDocument()

        val margin = 36f
        val contentWidth = pageWidth - margin * 2

        val paintTitle = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = android.graphics.Color.BLACK
            textSize = 20f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }

        val paintH = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = android.graphics.Color.BLACK
            textSize = 13f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }

        val paintBody = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = android.graphics.Color.BLACK
            textSize = 12f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        }

        val paintMuted = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = android.graphics.Color.argb(180, 0, 0, 0)
            textSize = 10.5f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        }

        val paintLine = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = android.graphics.Color.argb(60, 0, 0, 0)
            strokeWidth = 1.5f
        }

        fun footerText(): String {
            val ts = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"))
            return "Generated by ExpenseTracker • $ts"
        }

        // Layout helpers
        val rowHeight = 20f
        val headerHeight = 28f

        var pageNumber = 1
        var y = margin

        fun startPage(): PdfDocument.Page {
            val pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
            val page = doc.startPage(pageInfo)
            y = margin
            return page
        }

        fun finishPage(page: PdfDocument.Page) {
            // footer
            val canvas = page.canvas
            val footerY = pageHeight - margin + 10f
            canvas.drawLine(margin, pageHeight - margin, pageWidth - margin, pageHeight - margin, paintLine)
            canvas.drawText(footerText(), margin, footerY, paintMuted)
            canvas.drawText("Page $pageNumber", pageWidth - margin - 60f, footerY, paintMuted)

            doc.finishPage(page)
            pageNumber++
        }

        fun ensureSpaceOrNewPage(currentPage: PdfDocument.Page, needed: Float): PdfDocument.Page {
            val bottomLimit = pageHeight - margin - 24f
            return if (y + needed <= bottomLimit) {
                currentPage
            } else {
                finishPage(currentPage)
                startPage()
            }
        }

        var page = startPage()
        val canvas = page.canvas

        // ----- Header -----
        canvas.drawText(title, margin, y + 18f, paintTitle)
        y += 30f

        canvas.drawText("Month", margin, y + 14f, paintH)
        canvas.drawText(monthLabel, margin + 90f, y + 14f, paintBody)
        y += 22f

        canvas.drawLine(margin, y, pageWidth - margin, y, paintLine)
        y += 18f

        // ----- Summary box -----
        canvas.drawText("Summary", margin, y + 14f, paintH)
        y += 22f

        fun summaryRow(label: String, value: String) {
            canvas.drawText(label, margin, y + 12f, paintBody)
            val valueX = margin + contentWidth - min(contentWidth, paintBody.measureText(value))
            canvas.drawText(value, valueX, y + 12f, paintBody)
            y += 18f
        }

        summaryRow("Income", incomeText)
        summaryRow("Expenses", expenseText)
        summaryRow("Balance", balanceText)

        y += 6f
        canvas.drawLine(margin, y, pageWidth - margin, y, paintLine)
        y += 18f

        // ----- Categories table -----
        canvas.drawText("Spending by category", margin, y + 14f, paintH)
        y += 20f

        // Table header
        fun tableHeader() {
            // background line
            canvas.drawLine(margin, y + headerHeight, pageWidth - margin, y + headerHeight, paintLine)

            canvas.drawText("Category", margin, y + 18f, paintH)
            val amountHeader = "Amount"
            val amountX = margin + contentWidth - paintH.measureText(amountHeader)
            canvas.drawText(amountHeader, amountX, y + 18f, paintH)
            y += headerHeight
        }

        tableHeader()

        if (categories.isEmpty()) {
            canvas.drawText("No category data for this period.", margin, y + 14f, paintMuted)
            y += 20f
        } else {
            categories.forEachIndexed { idx, (label, amountText) ->
                page = ensureSpaceOrNewPage(page, rowHeight + 10f)
                val c = page.canvas

                // If a new page started, we need a fresh header
                if (y == margin) {
                    // page title small
                    c.drawText(title, margin, y + 16f, paintH)
                    y += 26f
                    c.drawText("Spending by category (continued)", margin, y + 14f, paintH)
                    y += 18f
                    tableHeader()
                }

                c.drawText(label, margin, y + 14f, paintBody)

                val amountX = margin + contentWidth - paintBody.measureText(amountText)
                c.drawText(amountText, amountX, y + 14f, paintBody)

                // row divider
                c.drawLine(margin, y + rowHeight, pageWidth - margin, y + rowHeight, paintLine)
                y += rowHeight
            }
        }

        finishPage(page)

        // Write + close
        doc.writeTo(output)
        doc.close()
        output.flush()
    }
}
